export const GET_PLAYERS_PER_TEAM_PENDING = "GET_PLAYERS_PER_TEAM_PENDING";
export const GET_PLAYERS_PER_TEAM_SUCCESS = "GET_PLAYERS_PER_TEAM_SUCCESS";
export const GET_PLAYERS_PER_TEAM_ERROR = "GET_PLAYERS_PER_TEAM_ERROR";
