export const GET_PLAYERS_AVAILABLE_PENDING = "GET_PLAYERS_AVAILABLE_PENDING";
export const GET_PLAYERS_AVAILABLE_SUCCESS = "GET_PLAYERS_AVAILABLE_SUCCESS";
export const GET_PLAYERS_AVAILABLE_ERROR = "GET_PLAYERS_AVAILABLE_ERROR";
